### ISSUE TITLE
Great addons, but stopped working

### ISSUE THREAD

**Issue by NuxRo** [goldenratio/xbmc-web-remote#20]
Hi,

This is a great addon, _very_ handy, alas it has stopped working a little while back.
It coincided with upgrade to Kodi on my HTPC, but I think it has to do more with Firefox, running tcpdump on both my laptop as well as the HTPC indicates no traffic on port 9090 whatsoever.

Launching Firefox in a terminal spits out the following:

console.error: xbmc-remote: 
  DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/Promise-backend.js", line 870, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 86, in startup/</<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 145, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 684, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 318, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 267, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://jid1-xjowf7m9ffgmvq-at-jetpack/xbmc-remote/lib/main.js", line 8, in null
    var widgets = require("sdk/widget");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 591, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 318, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 267, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);

**Comment by goldenratio** [comment]
Hi,
I fixed this while back https://github.com/goldenratio/xbmc-web-remote/commit/a7a95db0500c93f7faa7a58ab3f403576f8c8258

Add-on is under Firefox review process. They are really slow in review process :(

**Comment by goldenratio** [comment]
btw also you could try the live web version,
http://goldenratio.github.io/xbmc-web-remote/remote/remote.html if it works here... then the problem is with the add-on.

**Comment by NuxRo** [comment]
Thanks, that seems to be working. Do you have a newer xpi lying around? Seems like waiting for Mozilla to approve the addon will take a while.

**Comment by goldenratio** [comment]
ya sure, https://dl.dropboxusercontent.com/u/65931953/kassi-xbmc-remote.xpi 
But you could always build it yourself https://github.com/goldenratio/xbmc-web-remote/blob/master/README.md

**Comment by NuxRo** [comment]
Thanks for that.
The build procedure seems convoluted, don't know who ant is and what it wants.
Plus I always go for running random binaries off the internet from people I never met. More in line with contemporary trends. :)

Thanks
